name: check

on:
  push:
    branches: ['**']
  pull_request:

jobs:
  core:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12', '3.13']
    defaults:
      run:
        working-directory: splitpy-core
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: pipx install poetry
      - run: poetry install --no-interaction
      - run: poetry run ruff check .
      - run: poetry run black --check .
      - run: poetry run pytest

  app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12', '3.13']
    defaults:
      run:
        working-directory: splitpy-app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: pipx install poetry
      - run: poetry install --no-interaction
      - run: poetry run ruff check .
      - run: poetry run black --check .
      - run: poetry run pytest
